config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'

  # resources :static_pages
  resources :users
  resources :applicants

  # Sets the default homepage when users access https://rugby-project-bradywalsh.c9users.io
  root 'static_pages#home'
  get '/users/new', to: 'users#new'
  
  # Changed the default URL/PATH of the Static pages
  get    '/about',     to: 'static_pages#about'
  get    '/contact',   to: 'static_pages#contact'
  get    '/schedule',  to: 'static_pages#schedule'
  get    '/roster',    to: 'static_pages#roster'
  get    '/media',     to: 'static_pages#media'
  get    '/awards',    to: 'static_pages#awards'
  get    '/login',     to: 'sessions#new'
  post   '/login',     to: 'sessions#create'
  delete '/logout',    to: 'sessions#destroy'
end

app/models/applicant.rb
class Applicant < ApplicationRecord
    before_save { email.downcase! }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :name, presence: true, length: { maximum: 50 }
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }
                      
    validates :year, presence: true
    validates :school, presence: true
    validates :experience, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    before_save { email.downcase! }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :name, presence: true, length: { maximum: 50 }
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }
    validates :password, presence: true, length: { minimum: 6 }
    has_secure_password
    
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                      BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end
end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
    include ApplicantsHelper

    def new
        @applicant = Applicant.new
    end
    
    def create
        @applicant = Applicant.new(applicant_params)
        if @applicant.save
            flash.notice = "Thanks #{@applicant.name.titleize}, you made the greatest decision of your life!"
            redirect_to root_path
        else
            render 'new'
        end
    end
    
    def index
        @applicants = Applicant.all
    end
    
    def show
        @applicant = Applicant.find(params[:id])
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_path
    else
      flash.now[:danger] = "invalid email/password combination"
      render 'new'
    end
  end
  
  def destroy
    log_out
    redirect_to root_url
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
  
  def contact
  end
  
  def schedule
  end
  
  def roster
  end
  
  def media
  end
  
  def awards
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
    
    def applicant_params
        params.require(:applicant).permit(:name, :email, :school, :year, :experience)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def full_title(page_title = '')
        base_title = "Wentworth Men's Rugby"
        if page_title.empty?
            base_title
        else
            page_title + " | " + base_title
        end
    end
    
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
    def log_in(user)
        session[:user_id] = user.id
    end
    
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    
    # Returns true if the user is logged in, false otherwise
    def logged_in?
        !current_user.nil?
    end
    
    def log_out
        session.delete(:user_id)
        @current_user = nil
    end
    
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/applicants/index.html.erb
<% @applicants.each do |applicant| %>
    <%= link_to applicant.name, applicant %>
<% end %>

app/views/applicants/new.html.erb
<div class="jumbotron text-center">
    <h1>Sign-up for the team!</h1>
    
    <%= form_for(@applicant) do |f| %>
    
        <p>
            <%= f.label :name %>
            <%= f.text_field :name %>
        </p>
        
        <p>
            <%= f.label :email %>
            <%= f.text_field :email %>
        </p>
        
        <p>
            <%= f.label :school %>
            <%= f.select :school, ['Wentworth','MCPHS','MassArt','Wheelock', 'Emmanuel'], :prompt => 'Select One' %>
        </p>
        
        <p>
            <%= f.label :year %>
            <%= f.select :year, ['Freshman', 'Sophomore', 'Junior', 'Senior', '5th Year'], :prompt => 'Select One' %>
        </p>
        
        <p>
            <%= f.label :experience %><br>
            <%= f.text_area :experience %>
        </p>
        
        <%= f.submit "Submit" %>
    
    <% end %>    
</div>

app/views/applicants/show.html.erb
<div class="row text-center">
    <p>
        <strong>Name:</strong>
        <%= @applicant.name %>
    </p>
    
    <p>
        <strong>Email:</strong>
        <%= @applicant.email %>
    </p>
    
    <p>
        <strong>School:</strong>
        <%= @applicant.school %>
    </p>
    
    <p>
        <strong>Year:</strong>
        <%= @applicant.year %>
    </p>
    
    <p>
        <strong>Experience:</strong>
        <%= @applicant.experience %>
    </p>
    
    <%= link_to "Back", applicants_path %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
    <div class="footer-logos">
        <ul>
            <li class = "footer-logo1"><%= link_to image_tag('footer_logo_01.png'), "http://www.ncaa.org/d3" %></li>
            <li class = "footer-logo2"><%= link_to image_tag('footer_logo_02.png'), "http://cccathletics.com" %></li>
            <li class = "footer-logo3"><%= link_to image_tag('footer_logo_03.png'), "http://www.thegnac.com" %></li>
            <li class = "footer-logo3"><%= link_to image_tag('footer_logo_04.jpg', height: 80, width: 130), "http://www.colonialcoastrugby.com/" %></li>
        </ul>
    </div>
    
    <div class="footer-text navbar navbar-fixed-bottom">
        <span class="team-info">© Wentworth Institute of Technology | 550 Huntington Avenue | Boston, MA 02115 | 617-989-4590</span>
        <nav>
            <ul id="footer-links">
                <li><%= link_to "Home", root_path %></li>
                <li>|</li>
                <li><%= link_to "About", about_path %></li>
                <li>|</li>
                <li><a href="#top">Go to top</a></li>
            </ul>
        </nav>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class = "top-header">
    <%= link_to "W.I.T Rugby", root_path, id: 'logo' %>
  </div>
  <div class="container">
    <nav>
      <ul class="nav navbar-nav center-block">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Schedule", schedule_path %></li>
        <li><%= link_to "Roster", roster_path %></li>
        <li><%= link_to "Awards", awards_path %></li>
        <li><%= link_to "Media", media_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Applicants", applicants_path %></li>
              <li><%= link_to "Settings", "#" %></li>
              <li class="divider"></li>
              <li><%= link_to "Log out", logout_path, method: "delete" %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", login_path  %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

    

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <!-- This is the flash notification for the errors on the website -->
      <% flash.each do |key, value| %>
        <div class="center-block alert alert-<%= key %>"><%= value %></div>
      <% end %>
      
      <!-- This yield is the content to the website -->
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<div class="center jumbotron">
    <h1>About Us</h1>
    <p>Wentworth Men’s Rugby is a club sport founded in 5000 B.C. by Zeus. 
    Since then, the club has been a great way for students of the COF to learn 
    team camaraderie and sportsmanship while playing a less traditional sport. 
    Wentworth Rugby is open to all, regardless of experience. We are involved
    in volunteer work throughout the greater Boston area and conduct fundraising 
    annually. If you have even the slightest interest in playing the game of rugby 
    please go to the contact page to email one of the team leaders. See you at practice! 
</p>

</div>
    

app/views/static_pages/awards.html.erb
<% provide(:title, "Awards") %>
<h1>Awards</h1>


<div class="row">
    <%= image_tag('awards_teampic.jpg', class: "col-xs-4 col-md-4 col-lg-4 vcenter", id: "team-pic") %>
    <p class="col-xs-8 col-md-8 col-lg-8 pull-right vcenter">
    The team’s most recent accomplishment came in the Spring of 2016
    when the Leopards entered into the Providence, RI “Beast of the East” 
    tournament. After defeating Mass Maritime 42-19 and Fitchburg State 49-0, 
    the Men’s team took home their first Championship Plaque in club history.
    
    
    </p>
    
    
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>Aliquam id cursus dolor, eget tristique mauris. Fusce sollicitudin quam quis
elementum pretium. Maecenas suscipit nibh tortor, sollicitudin consequat sapien
mattis eget. Suspendisse nec molestie elit. Donec sit amet augue nulla. Fusce
quis turpis eget lorem pellentesque tempor sit amet in urna. Nulla facilisi.
Suspendisse urna augue, maximus in facilisis sed, condimentum eu mauris. Quisque
interdum leo eu nulla porttitor, non aliquam metus interdum. Nullam sagittis
massa ac ultricies posuere. Suspendisse potenti.</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron col-xs-10 col-sm-10 col-md-10">
    <h1>Home</h1>
    <p> Vivamus eget libero id enim malesuada vestibulum et in purus. Lorem ipsum
    dolor sit amet, consectetur adipiscing elit. Nunc convallis, justo nec ornare
    sollicitudin, enim tellus convallis arcu, tempor luctus purus libero iaculis
    tortor. Quisque consequat vehicula lacus in rhoncus. Vestibulum mattis mattis
    ipsum, ut mollis lectus iaculis gravida. Aliquam lectus nisi, ultrices quis nunc
    sed, egestas posuere velit. Pellentesque ligula turpis, pellentesque vitae
    sapien non, eleifend sollicitudin risus. Phasellus sit amet lectus quis augue
    lobortis lobortis. Praesent vulputate eros a ligula vehicula scelerisque.
    Suspendisse id massa accumsan, accumsan leo id, accumsan quam. Quisque faucibus
    eros tellus, sed pharetra turpis tempus eu.</p>
    <%= link_to "Apply", new_applicant_path, class: "btn btn-lg btn-primary" %>
</div>
<div class="feed-wrapper col-xs-2 col-sm-2 col-md-2">
    <div class = "container-header"><h1>League Info & Results</h1></div>
    <div class = twitter-feed>
        <a class="twitter-timeline" href="https://twitter.com/colonialcoastr1">Tweets by colonialcoastr1</a> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
    </div>
</div>
<div class="team-standings">
    <table class="table table-bordered">
    <thead>
      <tr>
        <th>Team</th>
        <th>Conference(W-L-T)</th>
        <th>Overall(W-L-T)</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>UMASS Dartmouth</td>
        <td>4-0-0</td>
        <td>4-3-0</td>
      </tr>
      <tr>
        <td>Wentworth</td>
        <td>3-1-0</td>
        <td>3-4-0</td>
      </tr>
      <tr>
        <td>Wheaton</td>
        <td>2-2-0</td>
        <td>2-5-0</td>
      </tr>
      <tr>
        <td>Mass Maritime</td>
        <td>1-3-0</td>
        <td>3-4-0</td>
      </tr>
      <tr>
        <td>Johnson & Wales</td>
        <td>0-4-0</td>
        <td>0-7-0</td>
      </tr>
    </tbody>
  </table>
</div>

app/views/static_pages/media.html.erb
<% provide(:title, "Media") %>
<h1>Media</h1>
<p>Phasellus congue laoreet vestibulum. Donec efficitur lacus in sem aliquet, at
tempus nisl consequat. Quisque laoreet, sapien vitae pharetra vestibulum, libero
elit tristique urna, eu ornare leo orci a neque. Nunc in ornare dolor. Integer a
egestas mi, et faucibus est. Praesent pretium est metus, ultricies accumsan
lectus hendrerit nec. Integer suscipit neque lorem, dapibus vulputate urna
congue euismod. Pellentesque sollicitudin ante maximus eros tincidunt lacinia.
Nullam sagittis malesuada quam, eget mattis sem lacinia a. Sed sem urna, posuere 
nec aliquet sit amet, finibus in lectus. Nam interdum aliquet auctor. Etiam
magna lacus, ultrices eget ex ut, posuere venenatis urna. Etiam porttitor
laoreet massa ut ultrices.</p>

app/views/static_pages/roster.html.erb
<% provide(:title, "Roster") %>
<h1>Roster</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum in
lacinia lacus. Etiam volutpat laoreet lacus, sed dignissim lorem iaculis eu.
Aliquam sapien quam, auctor eu pharetra vitae, ornare quis turpis. Donec viverra
massa in lectus feugiat consectetur. Proin congue nunc arcu, vitae venenatis leo
sagittis volutpat. Vivamus ornare ut libero a ultrices. Sed scelerisque lorem
nulla, ut aliquet sapien ullamcorper quis. Aenean rutrum faucibus nisi id
eleifend. Aenean maximus vel odio ut suscipit. Aliquam nunc nunc, vulputate in
purus id, suscipit tincidunt orci. Mauris a mattis nibh, ut porttitor lorem.
Vestibulum hendrerit massa justo, sed bibendum lacus scelerisque nec. Sed ligula
purus, scelerisque id purus id, tincidunt viverra lectus. Phasellus bibendum
fringilla tortor, vestibulum rhoncus purus. Nullam rutrum mi sapien, at eleifend
ligula ullamcorper a.</p>

app/views/static_pages/schedule.html.erb
<% provide(:title, "Schedule") %>
<h1>2016-2017 Schedule</h1>
<div class="table-container container">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Date</th>
        <th>Time</th>
        <th>Opponent</th>
        <th>Result</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>9/17</td>
        <td>7:00 AM</td>
        <td>
            <div class = "team-logo">
                <img src="http://cdnak1.psbin.com/logos/id/zimupjocdmsfkpy1.png"/>
            </div>
            <span class = "school-name"> at Johnson & Wales</span>
        </td>
        <td>17-18</td>
      </tr>
      <tr>
        <td>8/1</td>
        <td>7:00 PM</td>
        <td>
            <div class = "team-logo">
                <img src="http://cdnak1.psbin.com/logos/id/88t62m3kzbw5xysh.png"/>
            </div>
            <span class = "school-name"> at Mass Maritime</span>
        </td>
        <td>W 17-7</td>
      </tr>
      <tr>
        <td>8/23</td>
        <td>7:00 PM</td>
        <td>
            <div class = "team-logo">
                <img src="http://cdnak1.psbin.com/logos/id/ugg957ps01kkfcvt.png"/>
            </div>
            <span class = "school-name"> Salve Regina</span>
        </td>
        <td>W 17-9</td>
      </tr>
      <tr>
        <td>01/01</td>
        <td>00:00 AM</td>
        <td>
            <div class = "team-logo">
                <img src="http://cdnak1.psbin.com/logos/id/ojo2p1sve9tu26a2.png"/>
            </div>
            <span class = "school-name"> at Emmanuel College</span>
        </td>
      </tr>
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>